- name: Deploy virtual server to F5 BIG-IP
  hosts: bigip
  connection: local
  gather_facts: no

  # vars:
  #   vip_name: "demo_vs"                           # Name of the virtual server
  #   vip_address: "{{ bigip_vs_ip }}"              # Virtual server IP address
  #   vip_port: "80"                                # Port for the virtual server
  #   pool_name: "demo_pool"                        # Name of the load balancing pool

  #   # Define pool members
  #   pool_members:
  #     - { host: "10.0.12.101", port: 80 }
  #     - { host: "10.0.12.102", port: 80 }

  tasks:
    # - name: Get iRule file list
    #   find:
    #     paths: irules
    #     patterns: "*.tcl"
    #   register: found_irules

    # - name: Initialize iRule dictionary
    #   set_fact:
    #     irule_objects: {}

    # - name: Load iRule content into dictionary
    #   set_fact:
    #     irule_objects: "{{ irule_objects | combine({ item.path | basename | regex_replace('\\.tcl$', ''): lookup('file', item.path) }) }}"
    #   loop: "{{ found_irules.files }}"

    # - name: Render AS3 JSON from template
    #   template:
    #     src: templates/as3_template.json.j2
    #     dest: rendered_as3.json

    # - name: POST AS3 declaration to BIG-IP
    #   uri:
    #     url: "https://{{ bigip_host }}/mgmt/shared/appsvcs/declare"
    #     method: POST
    #     user: "{{ bigip_user }}"
    #     password: "{{ bigip_password }}"
    #     force_basic_auth: yes
    #     body_format: json
    #     body: "{{ lookup('file', 'rendered_as3.json') | from_json }}"
    #     validate_certs: no
    #     status_code: [200, 202]

    # - name: Set provider details (connection credentials for F5 BIG-IP)
    #   no_log: true
    #   set_fact:
    #     provider:
    #       server: "{{ bigip_host }}"
    #       user: "{{ bigip_user }}"
    #       password: "{{ bigip_password }}"
    #       server_port: 443
    #       validate_certs: false
    #       no_f5_teem: true

    # - name: Create pool (load balancing group)
    #   f5networks.f5_modules.bigip_pool:
    #     provider: "{{ provider }}"
    #     name: "{{ pool_name }}"
    #     lb_method: "round-robin"
    #     monitors: "/Common/http"
    #     state: "present"

    # - name: Add pool members to the pool
    #   f5networks.f5_modules.bigip_pool_member:
    #     provider: "{{ provider }}"
    #     pool: "{{ pool_name }}"
    #     host: "{{ item.host }}"
    #     port: "{{ item.port }}"
    #     state: "present"
    #   loop: "{{ pool_members }}"

    # - name: Create virtual server (VIP)
    #   f5networks.f5_modules.bigip_virtual_server:
    #     provider: "{{ provider }}"
    #     name: "{{ vip_name }}"
    #     destination: "{{ vip_address }}"
    #     port: "{{ vip_port }}"
    #     pool: "{{ pool_name }}"
    #     profiles:
    #       - http
    #       - tcp
    #     snat: "Automap"
    #     state: "present"
